development:
  adapter: postgresql
  encoding: unicode
  database: d2jtjvlmpktkvp
  pool: 5
  username: uzrcdzjvmnorvp
  password: Eao4YkxIfIzIeYvqNotU_0yDXH

test:
  adapter: postgresql
  encoding: unicode
  database: d2jtjvlmpktkvp
  pool: 5
  username: uzrcdzjvmnorvp
  password: Eao4YkxIfIzIeYvqNotU_0yDXH

production:
  adapter: postgresql
  encoding: unicode
  database: d2jtjvlmpktkvp
  pool: 5
  username: uzrcdzjvmnorvp
  password: Eao4YkxIfIzIeYvqNotU_0yDXH